/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare function encodeBase32Uppercase(input: Uint8Array): string
export declare function encodeBase32Lowercase(input: Uint8Array): string
export declare function encodeBase32LowercaseNoPadding(input: Uint8Array): string
export declare function encodeBase32UppercaseNoPadding(input: Uint8Array): string
export declare function decodeBase32(input: string): Array<number>
export declare function decodeBase32IgnorePadding(input: string): Array<number>
export declare function decodeHex(hex: string): string
export declare function encodeHexUpperCase(hex: string): string
export declare function encodeHexLowerCase(hex: string): string
