/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare function decodeHex(hex: string): string
export declare function encodeHexUpperCase(hex: string): string
export declare function encodeHexLowerCase(hex: string): string
