/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare function hexToString(hex: string): string
export declare function stringToHex(s: string): string
export declare function toUppercaseHex(hex: string): string
export declare function toLowercaseHex(hex: string): string
